default['monkeybar']['application_name']           = 'monkeybar'
default['monkeybar']['mgmt_port']                  = '80'
default['monkeybar']['home'] = '/srv/www/monkeybar/current'
default['monkeybar']['route'] = 'start'
default['monkeybar']['nodejs']['node_env'] = 'dev'
